import type { TrainingProgram, Registration, User, DashboardStats } from './types';

export const currentUser: User = {
  id: 'user-1',
  name: 'أحمد محمد',
  email: 'ahmed@company.com',
  department: 'تقنية المعلومات',
  role: 'admin',
};

export const mockPrograms: TrainingProgram[] = [
  {
    id: 'prog-1',
    title: 'القيادة الفعّالة',
    description: 'برنامج تدريبي شامل لتطوير المهارات القيادية والإدارية للمشرفين والمدراء',
    category: 'القيادة والإدارة',
    duration: '5 أيام',
    instructor: 'د. سارة العلي',
    location: 'قاعة التدريب الرئيسية',
    status: 'active',
    createdAt: '2024-01-15',
    objectives: [
      'فهم أساسيات القيادة الفعالة',
      'تطوير مهارات التواصل مع الفريق',
      'إدارة الصراعات وحل المشكلات',
      'بناء فرق عمل متماسكة',
    ],
    prerequisites: ['خبرة لا تقل عن سنتين في المجال', 'موافقة المدير المباشر'],
    batches: [
      {
        id: 'batch-1-1',
        name: 'الدفعة الأولى',
        startDate: '2024-03-01',
        endDate: '2024-03-05',
        maxParticipants: 20,
        currentParticipants: 18,
        status: 'completed',
      },
      {
        id: 'batch-1-2',
        name: 'الدفعة الثانية',
        startDate: '2024-04-15',
        endDate: '2024-04-19',
        maxParticipants: 20,
        currentParticipants: 15,
        status: 'ongoing',
      },
      {
        id: 'batch-1-3',
        name: 'الدفعة الثالثة',
        startDate: '2024-06-01',
        endDate: '2024-06-05',
        maxParticipants: 20,
        currentParticipants: 5,
        status: 'upcoming',
      },
    ],
  },
  {
    id: 'prog-2',
    title: 'إدارة المشاريع الاحترافية PMP',
    description: 'برنامج معتمد للتحضير لشهادة إدارة المشاريع الاحترافية',
    category: 'إدارة المشاريع',
    duration: '10 أيام',
    instructor: 'م. خالد الراشد',
    location: 'عن بُعد',
    status: 'active',
    createdAt: '2024-01-20',
    objectives: [
      'فهم منهجيات إدارة المشاريع',
      'التحضير لاختبار PMP',
      'تطبيق عملي على مشاريع حقيقية',
    ],
    batches: [
      {
        id: 'batch-2-1',
        name: 'الدفعة الأولى',
        startDate: '2024-05-01',
        endDate: '2024-05-14',
        maxParticipants: 15,
        currentParticipants: 12,
        status: 'upcoming',
      },
    ],
  },
  {
    id: 'prog-3',
    title: 'مهارات التواصل الفعّال',
    description: 'تعلم أساسيات التواصل الفعال في بيئة العمل',
    category: 'المهارات الشخصية',
    duration: '3 أيام',
    instructor: 'أ. نورة السالم',
    location: 'قاعة التدريب B',
    status: 'active',
    createdAt: '2024-02-01',
    objectives: [
      'تحسين مهارات الاستماع',
      'التحدث بثقة ووضوح',
      'كتابة رسائل بريد إلكتروني احترافية',
    ],
    batches: [
      {
        id: 'batch-3-1',
        name: 'الدفعة الأولى',
        startDate: '2024-04-20',
        endDate: '2024-04-22',
        maxParticipants: 25,
        currentParticipants: 20,
        status: 'ongoing',
      },
      {
        id: 'batch-3-2',
        name: 'الدفعة الثانية',
        startDate: '2024-05-20',
        endDate: '2024-05-22',
        maxParticipants: 25,
        currentParticipants: 8,
        status: 'upcoming',
      },
    ],
  },
  {
    id: 'prog-4',
    title: 'الأمن السيبراني للمبتدئين',
    description: 'مقدمة شاملة في مجال الأمن السيبراني وحماية البيانات',
    category: 'تقنية المعلومات',
    duration: '4 أيام',
    instructor: 'م. فهد العتيبي',
    location: 'مختبر الحاسب',
    status: 'active',
    createdAt: '2024-02-10',
    objectives: [
      'فهم أساسيات الأمن السيبراني',
      'التعرف على أنواع الهجمات الإلكترونية',
      'تطبيق أفضل ممارسات الحماية',
    ],
    batches: [
      {
        id: 'batch-4-1',
        name: 'الدفعة الأولى',
        startDate: '2024-06-10',
        endDate: '2024-06-13',
        maxParticipants: 15,
        currentParticipants: 3,
        status: 'upcoming',
      },
    ],
  },
  {
    id: 'prog-5',
    title: 'إدارة الوقت والإنتاجية',
    description: 'استراتيجيات فعالة لإدارة الوقت وزيادة الإنتاجية',
    category: 'المهارات الشخصية',
    duration: '2 يوم',
    instructor: 'د. منى الحربي',
    location: 'عن بُعد',
    status: 'draft',
    createdAt: '2024-02-15',
    objectives: [
      'تحديد الأولويات بفعالية',
      'التخلص من المشتتات',
      'استخدام أدوات إدارة الوقت',
    ],
    batches: [],
  },
];

export const mockRegistrations: Registration[] = [
  {
    id: 'reg-1',
    programId: 'prog-1',
    programTitle: 'القيادة الفعّالة',
    batchId: 'batch-1-2',
    batchName: 'الدفعة الثانية',
    userId: 'user-2',
    userName: 'محمد العمري',
    userDepartment: 'الموارد البشرية',
    status: 'approved',
    registeredAt: '2024-03-20',
    approvedBy: 'user-1',
    approvedAt: '2024-03-21',
  },
  {
    id: 'reg-2',
    programId: 'prog-1',
    programTitle: 'القيادة الفعّالة',
    batchId: 'batch-1-3',
    batchName: 'الدفعة الثالثة',
    userId: 'user-3',
    userName: 'فاطمة الزهراني',
    userDepartment: 'المالية',
    status: 'pending',
    registeredAt: '2024-04-01',
  },
  {
    id: 'reg-3',
    programId: 'prog-2',
    programTitle: 'إدارة المشاريع الاحترافية PMP',
    batchId: 'batch-2-1',
    batchName: 'الدفعة الأولى',
    userId: 'user-4',
    userName: 'عبدالله القحطاني',
    userDepartment: 'تقنية المعلومات',
    status: 'pending',
    registeredAt: '2024-04-05',
  },
  {
    id: 'reg-4',
    programId: 'prog-3',
    programTitle: 'مهارات التواصل الفعّال',
    batchId: 'batch-3-1',
    batchName: 'الدفعة الأولى',
    userId: 'user-5',
    userName: 'سارة الدوسري',
    userDepartment: 'خدمة العملاء',
    status: 'approved',
    registeredAt: '2024-04-10',
    approvedBy: 'user-1',
    approvedAt: '2024-04-11',
  },
  {
    id: 'reg-5',
    programId: 'prog-1',
    programTitle: 'القيادة الفعّالة',
    batchId: 'batch-1-1',
    batchName: 'الدفعة الأولى',
    userId: 'user-6',
    userName: 'ياسر المطيري',
    userDepartment: 'المبيعات',
    status: 'completed',
    registeredAt: '2024-02-15',
    approvedBy: 'user-1',
    approvedAt: '2024-02-16',
  },
];

export const mockStats: DashboardStats = {
  totalPrograms: 5,
  activePrograms: 4,
  totalRegistrations: 48,
  pendingApprovals: 2,
  completedTrainings: 18,
  totalEmployees: 150,
};

export const categories = [
  'الكل',
  'القيادة والإدارة',
  'إدارة المشاريع',
  'المهارات الشخصية',
  'تقنية المعلومات',
  'المالية والمحاسبة',
];
